name: Jenkins Logs

on:
  workflow_run:
    workflows: ["YourWorkflowName"]
    types:
      - completed

jobs:
  fetch_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Jenkins Logs
        run: |
          # Replace the Jenkins URL and log file path with the appropriate values
          jenkins_url="https://gkerefappscicd.jaas-gcp.cloud.sap.corp"
          log_file_path="/view/test/job/Test_log/1/consoleText"

          # Download the Jenkins log file using curl
          curl -O "${jenkins_url}${log_file_path}"

      - name: Archive Jenkins Logs
        uses: actions/upload-artifact@v2
        with:
          name: jenkins-logs
          path: path/to/jenkins/log
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: logs
          # Destination path
          path: /logs
